// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnet.Api.Infra.Database;

#nullable disable

namespace aspnet.Api.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230503220838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("aspnet.Api.Core.Entities.PostEntity", b =>
                {
                    b.Property<Guid?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("userid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("aspnet.Api.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("aspnet.Api.Core.Entities.PostEntity", b =>
                {
                    b.HasOne("aspnet.Api.Core.Entities.UserEntity", "user")
                        .WithMany("posts")
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("aspnet.Api.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
